# Generated by Django 2.1.5 on 2019-01-30 01:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190130_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharer_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
