# Generated by Django 2.1.5 on 2019-01-30 01:58

import django.contrib.postgres.fields
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190130_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharer_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=users.models.emptylist, size=None),
        ),
    ]
