# Generated by Django 2.1.5 on 2019-01-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190130_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='special',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
