# Generated by Django 2.1.5 on 2019-02-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_ride_sharer_passenget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='sharer_passenget',
            new_name='sharer_passenger',
        ),
    ]
