# Generated by Django 2.1.5 on 2019-02-01 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190131_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='total_psg',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)]),
        ),
    ]
